title: Shenzhe (Cho) Zhu
description: NLP researcher focusing on Trustworthy AI and MLLM/LLM security
repository: ShenzheZhu/shenzhezhu.github.io
google_analytics_id: # your google analytics ID
google_site_verification: # your google site verification ID
bing_site_verification: # your bing site verification ID
baidu_site_verification: # your baidu site verification ID

author:
  name: Shenzhe (Cho) Zhu
  avatar: images/selfie.jpg
  email: cho.zhu@mail.utoronto.ca
  github: ShenzheZhu
  google_scholar: WBZCniUAAAAJ
  linkedin: shenzhezhu0531
  city: Toronto
  university: University of Toronto
  description: I am a NLP researcher focusing on Trustworthy AI and MLLM/LLM security. Currently, I am a third-year Computer Science student at the University of Toronto. It's pleasure to collaborate with PRADA Lab at King Abdullah University of Science and Technology(KAUST). 